services:
  some-service:  
    privileged: # TODO maybe
    labels: # TODO
      com.domain.description: container desc
      com.domain.title: container title
    healthcheck: # TODO
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    depends_on: # TODO
      - a
      - b

volumes: # TODO
  some-storage:
