Image: nginx
Tag: latest
NamePrefix: sys--
Name: nginx-proxy
CurrentSuffix:
PreviousSuffix: -bak
Ports:
  - Host: 8080
    Container: 80
  - Host: 8443
    Container: 443
Volumes:
  - Source: /opt/nginx/data
    Destination: /data
    IsBind: true
    AutoCreate: true
  - Source: sys--nginx-ssl
    Destination: /ssl
    IsBind: false
    AutoCreate: true
EnvVars:
  TZ: Europe/Bucharest
Network:
  Name: services-dedicated-net
  Subnet: 172.20.1.1/24
  IpRange: 172.20.1.1/26
  IpAddress: 172.20.1.10
  Hostname:
  Alias:
  IsShared: false
ExtraHosts:
  host.docker.internal: host-gateway
Restart: unless-stopped
RunCommandOptions:
  - --memory 1024
