Image: nginx
Tag: latest
NamePrefix: sys--
BaseName: nginx-proxy
PrimarySuffix:
BackupSuffix: -bak
Ports:
  - Host: 8080
    Container: 80
  - Host: 8443
    Container: 443
Volumes:
  - Source: /opt/nginx/data
    Destination: /data
    IsMapping: true
    AutoCreate: true
  - Source: sys--nginx-ssl
    Destination: /ssl
    IsMapping: false
    AutoCreate: true
EnvVars:
  TZ: Europe/Bucharest
Network:
  Name: services-shared-net
  Subnet: 172.21.1.1/24
  IpRange: 172.21.1.1/26
  IpAddress: 172.21.1.10
  Hostname:
  Alias:
  IsShared: false
Restart: unless-stopped
