name: .NET dev-build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - uses: bbonkr/get-version-action@v1
        id: get_version
        with:
          project: "src/Adeotek.DevOpsTools/Adeotek.DevOpsTools.csproj"
      - name: logging
        run: |
          echo "Version=${{steps.get_version.outputs.version}}"