name: .NET publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Package
        run: dotnet pack --no-build --configuration Release src/Adeotek.DevOpsTools/Adeotek.DevOpsTools.csproj --output .
      - uses: bbonkr/get-version-action@v1
        id: get_version
        with:
          project: "src/Adeotek.DevOpsTools/Adeotek.DevOpsTools.csproj"
      - name: Publish to NuGet.org
        run: dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key ${{secrets.NUGET_API_KEY}} ./Adeotek.DevOpsTools.${{steps.get_version.outputs.version}}.nupkg
